/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QtQml/qqmlextensionplugin.h>

Q_IMPORT_QML_PLUGIN(contentPlugin)
Q_IMPORT_QML_PLUGIN(PiBoxPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_Ludo0Plugin)

Q_IMPORT_QML_PLUGIN(Quick3DAssets_Mesa_80cmPlugin)

Q_IMPORT_QML_PLUGIN(Quick3DAssets_OkeyPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_PawnPlugin)

